### ISSUE TITLE
Document CAJAL Methods

### ISSUE THREAD

**Issue by wrgr** [neurodata/CAJAL#14]

**Comment by alexbaden** [comment]
http://stackoverflow.com/questions/2417560/how-to-document-object-oriented-matlab-code

http://www.mathworks.com/matlabcentral/fileexchange/25925-using-doxygen-with-matlab

multiple options (logging here for safekeeping)

**Comment by jovo** [comment]
i'm hoping sphinx is the solution, cuz that is what we are using for m2g,
so knowledge transfer will be easiest.

On Fri, May 15, 2015 at 3:45 PM, Alex Baden notifications@github.com
wrote:

> http://stackoverflow.com/questions/2417560/how-to-document-object-oriented-matlab-code
> 
> http://www.mathworks.com/matlabcentral/fileexchange/25925-using-doxygen-with-matlab
> 
> multiple options (logging here for safekeeping)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/CAJAL/issues/14#issuecomment-102506815
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by alexbaden** [comment]
The plugin for Sphinx has some issues -- I tried it already and didn't get
good (or any) results. We can experiment.

Alex

**Comment by wrgr** [comment]
Yah.  There's a patch that's supposed to help.  I like Sphinx for all the
python stuff...would be nice to have a common setup.  One option is to
publish the overall pages in sphinx, and use some other tool to document
actual functions and methods.

Greg and I are sphinxing m2g tomorrow - feel free to join us!

Best,
Will

**Comment by wrgr** [comment]
done to first order
