### ISSUE TITLE
Create Reference LONI Object Detection Pipeline

### ISSUE THREAD

**Issue by wrgr** [neurodata/CAJAL#16]

**Comment by jovo** [comment]
bump?

**Comment by wrgr** [comment]
These are done for at least the first pass - but I think I'm deleting these from CAJAL and moving to vesicle?  Or no?

**Comment by jovo** [comment]
i trust your judgement.

On Fri, May 15, 2015 at 11:06 AM, William Gray notifications@github.com
wrote:

>  These are done for at least the first pass - but I think I'm deleting
> these from CAJAL and moving to vesicle?  Or no?
> 
> On Fri, May 15, 2015 at 10:44 AM, joshua vogelstein
> notifications@github.com wrote:
> 
> > ## bump?
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/openconnectome/CAJAL/issues/16#issuecomment-102417880
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/CAJAL/issues/16#issuecomment-102424723
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by jovo** [comment]
@willgray this is now ilastik object detect?

**Comment by wrgr** [comment]
leave it open.  that or vesicle.  but either way part of macho, not cajal

**Comment by wrgr** [comment]
done in vesicle
