### ISSUE TITLE
replace CAJAL3D with CAJAL everywhere

### ISSUE THREAD

**Issue by jovo** [neurodata/CAJAL#18]

**Comment by alexbaden** [comment]
This will break a lot of stuff. I'm going to look into aliasing it somehow.

Alex

**Comment by wrgr** [comment]
I will poke at this too.  I may be able to do a global find-replace.  The
issue is that this is what Anish, etc. use, so we'll have to individually
reach out.  We might be able to get away with it given that it's only a
handful of people...

Best,
Will

**Comment by alexbaden** [comment]
I think this is in good shape with the commit I just pushed to the 171 dev branch (https://github.com/openconnectome/CAJAL/commit/d293e4ebe471d30e92bd50d5b002595910b082af). You can now call cajal3d with either cajal3d() or cajal().
