### ISSUE TITLE
cloning objects

### ISSUE THREAD

**Issue by wrgr** [neurodata/CAJAL#20]
Deep copy seems to not quite work.  It works generally, but dynamic metadata and data type fields are 'sticky'

**Comment by wrgr** [comment]
I can help if you need me.

**Comment by alexbaden** [comment]
Can you provide an example?

**Comment by wrgr** [comment]
You is @willgray?

How would you like it?  A mat file or a set of CAJAL instructions/sample
code?

Best,
Will

**Comment by wrgr** [comment]
obe
