### ISSUE TITLE
Test the cajal / cajal3d subclass in ab-dev

### ISSUE THREAD

**Issue by alexbaden** [neurodata/CAJAL#21]
@willgray 
Checkout my branch, try running your stuff w/ it. It should be pretty close to master otherwise. I don't want to port the cajal / cajal3d subclass to the new version until we know it works! 

If it doesn't work assign this to me.

**Comment by alexbaden** [comment]
Hold off on this... something else is broken.

**Comment by wrgr** [comment]
ok.  I made you your own RAMON Objects...coming in the next 30 minutes.

Best,
Will
