### ISSUE TITLE
Improve bounds checking in all OCPQuery validation functions 

### ISSUE THREAD

**Issue by alexbaden** [neurodata/CAJAL#24]
Need to firm up what an "offset" and "dimension" means in terms of image size. For example, given a dataset with X offset 5 and X dimension 100, to get the entire X range do you call:

Xrange = [5, 100]
Xrange = [5,99]
Xrange = [5,101]

Or something else? @randalburns @kunallillaney

**Comment by wrgr** [comment]
Is this a quiz?  I vote 5,101.

NB historically CAJAL tries to match the OCP backend (the numbers we use
match the restful args), even though there are places where this is less
intuitive for an end-user.

Best,
Will

**Comment by kunallillaney** [comment]
[5,101] is correct.

**Comment by alexbaden** [comment]
No longer valid -- see #49
