### ISSUE TITLE
Run final test against v0.7-beta.1

### ISSUE THREAD

**Issue by kunallillaney** [neurodata/CAJAL#28]

**Comment by alexbaden** [comment]
All tests pass, except for the two kasthuri11 image cutout tests. I believe the problem there is a Z-indexing error with the way I setup kasthuri11 in my branch vs the way Dean had it setup in the previous branch. Once you migrate kasthuri11 we can look at it, but I suspect the kasthuri11 z-offset "should" be 1 to maintain compatibility with the existing data model.

**Comment by kunallillaney** [comment]
Great.
