### ISSUE TITLE
some tests fail, the output of matlab is below

### ISSUE THREAD

**Issue by jovo** [neurodata/CAJAL#29]
## Starting Unit Tests

The following unit test requires testMatlabInit.m to be configured:

testMatlabInit

Do you still want run this test? (Y or N):N

The following unit test(s) require the GUI and/or user interaction and are currently included:

testRAMONVolume

Do you still want run these tests? (Y or N):N

The following unit test require the distributed semaphore installed and configured in the API:

testOCPDistributedSemaphore

Do you still want run these test(s)? (Y or N):N
12 Test Suites selected out of 15 Test Suites discovered

<><><><> Running Test Suite 1 of 12 <><><><><><><><><><>
Test suite: testOCP
Test suite location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
13-Jul-2015 16:31:12

Starting test run with 73 test cases.
F....F..........F...
............F.F..F.F
..FF................
...FF.FF..FF.
FAILED in 334.366 seconds.

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testInit

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 34

Expected exception "OCP:ServerConnFail", but none thrown.

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testUploadDownloadAnnoBlockCutout

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 263

Inputs are not equal.

First input:
     0

Second input:
     1

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testDeleteRemovesVoxels

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 644

Inputs are not equal.

First input:
           0

Second input:
        6332

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testAnnotationSlice

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 1335

Inputs are not equal.

First input:
[0x1 double]

Second input:
[736x1 double]

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testOverlaySliceAlpha

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 1433

Asserted condition is not false.

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testIDqueryFromCutout

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 1588

Attempted to access ids2(0); index must be a positive integer or logical.

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testCutoutReturnsOneThingProperly

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 1678

Attempted to access inds(2); index out of bounds because numel(inds)=1.

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testCutoutvsDense

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 1813

Inputs are not equal.

First input:
     0

Second input:
        6360

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testCutoutvsDenseSingleSlice

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 1902

Inputs are not equal.

First input:
     0

Second input:
        6361

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testIDFilterCutoutDense

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 2810

Inputs are not equal.

First input:
     0

Second input:
           0        6418        6419        6420

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testIDFilterSlice

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 2852

Inputs are not equal.

First input:
     0

Second input:
     3

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testMerge

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 2922

Inputs are not equal.

First input:
     0

Second input:
        6435

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testCutoutRGBA

/Users/jovo/Research/Projects/Web-stuff/CAJAL/api/matlab/ocp/OCPNetwork.m at line 340
/Users/jovo/Research/Projects/Web-stuff/CAJAL/api/matlab/ocp/OCPNetwork.m at line 286
/Users/jovo/Research/Projects/Web-stuff/CAJAL/api/matlab/ocp/OCP.m at line 1233
/Users/jovo/Research/Projects/Web-stuff/CAJAL/api/matlab/ocp/OCP.m at line 229
/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 2949

Server Response 404 - NOT FOUND 
 Error Page: /var/folders/6d/4jmmx08x04194c4wpv3lpn700000gn/T/OcpUrlErrorResponse3170055919179173262.html

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testImageDataUpload

/Users/jovo/Research/Projects/Web-stuff/CAJAL/api/matlab/ocp/OCPNetwork.m at line 340
/Users/jovo/Research/Projects/Web-stuff/CAJAL/api/matlab/ocp/OCPNetwork.m at line 286
/Users/jovo/Research/Projects/Web-stuff/CAJAL/api/matlab/ocp/OCP.m at line 1233
/Users/jovo/Research/Projects/Web-stuff/CAJAL/api/matlab/ocp/OCP.m at line 229
/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 3056

Server Response 404 - NOT FOUND 
 Error Page: /var/folders/6d/4jmmx08x04194c4wpv3lpn700000gn/T/OcpUrlErrorResponse7598387533332776069.html

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m
Name:     testPropagate

/Users/jovo/Research/Projects/Web-stuff/CAJAL/api/matlab/ocp/OCPNetwork.m at line 340
/Users/jovo/Research/Projects/Web-stuff/CAJAL/api/matlab/ocp/OCPNetwork.m at line 286
/Users/jovo/Research/Projects/Web-stuff/CAJAL/api/matlab/ocp/OCP.m at line 1233
/Users/jovo/Research/Projects/Web-stuff/CAJAL/api/matlab/ocp/OCP.m at line 243
/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCP.m at line 3098

Server Response 404 - NOT FOUND 
 Error Page: /var/folders/6d/4jmmx08x04194c4wpv3lpn700000gn/T/OcpUrlErrorResponse8903846716108813861.html

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><><><> Running Test Suite 2 of 12 <><><><><><><><><><>
Test suite: testOCPHdf
Test suite location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCPHdf.m
13-Jul-2015 16:36:47

Starting test run with 9 test cases.
........F
FAILED in 2.047 seconds.

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCPHdf.m
Name:     testVolumeFromService

/Users/jovo/Research/Projects/Web-stuff/CAJAL/api/matlab/ocp/OCPHdf.m at line 269
/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCPHdf.m at line 232

HDF5 File format error.  Cannot parse object.

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><><><> Running Test Suite 3 of 12 <><><><><><><><><><>
Test suite: testOCPQuery
Test suite location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testOCPQuery.m
13-Jul-2015 16:36:49

Starting test run with 19 test cases.
...................
PASSED in 11.205 seconds.
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><><><> Running Test Suite 4 of 12 <><><><><><><><><><>
Test suite: testRAMONAttributedRegion
Test suite location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testRAMONAttributedRegion.m
13-Jul-2015 16:37:00

Starting test run with 1 test case.
.
PASSED in 0.002 seconds.
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><><><> Running Test Suite 5 of 12 <><><><><><><><><><>
Test suite: testRAMONBase
Test suite location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testRAMONBase.m
13-Jul-2015 16:37:00

Starting test run with 14 test cases.
..............
PASSED in 0.251 seconds.
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><><><> Running Test Suite 6 of 12 <><><><><><><><><><>
Test suite: testRAMONGeneric
Test suite location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testRAMONGeneric.m
13-Jul-2015 16:37:00

Starting test run with 5 test cases.
.....
PASSED in 0.178 seconds.
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><><><> Running Test Suite 7 of 12 <><><><><><><><><><>
Test suite: testRAMONNeuron
Test suite location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testRAMONNeuron.m
13-Jul-2015 16:37:01

Starting test run with 11 test cases.
...........
PASSED in 0.280 seconds.
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><><><> Running Test Suite 8 of 12 <><><><><><><><><><>
Test suite: testRAMONOrganelle
Test suite location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testRAMONOrganelle.m
13-Jul-2015 16:37:01

Starting test run with 15 test cases.
...............
PASSED in 0.607 seconds.
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><><><> Running Test Suite 9 of 12 <><><><><><><><><><>
Test suite: testRAMONSeed
Test suite location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testRAMONSeed.m
13-Jul-2015 16:37:02

Starting test run with 11 test cases.
...........
PASSED in 0.243 seconds.
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><><><> Running Test Suite 10 of 12 <><><><><><><><><><>
Test suite: testRAMONSegment
Test suite location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testRAMONSegment.m
13-Jul-2015 16:37:02

Starting test run with 16 test cases.
................
PASSED in 0.427 seconds.
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><><><> Running Test Suite 11 of 12 <><><><><><><><><><>
Test suite: testRAMONSynapse
Test suite location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/api/testRAMONSynapse.m
13-Jul-2015 16:37:02

Starting test run with 18 test cases.
..................
PASSED in 0.678 seconds.
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><><><> Running Test Suite 12 of 12 <><><><><><><><><><>
Test suite: testCubeCutout
Test suite location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/packages/testCubeCutout.m
13-Jul-2015 16:37:03

Starting test run with 11 test cases.
......FWarning: Directory already exists. 

> In testCubeCutout>testPreCalcCuboid_NoPad_End_CutoutOnly (line 295)
>   In FunctionHandleTestCase/runTestCase (line 112)
>   In TestCase/run (line 74)
>   In TestSuite/run (line 85)
>   In runtests (line 126)
>   In RUN_TESTS (line 258)
>   In run (line 96) 
> FFWarning: Directory already exists. 
> In testCubeCutout>testPreCalcCuboid_Pad_End_CutoutOnly (line 460)
>   In FunctionHandleTestCase/runTestCase (line 112)
>   In TestCase/run (line 74)
>   In TestSuite/run (line 85)
>   In runtests (line 126)
>   In RUN_TESTS (line 258)
>   In run (line 96) 
> FWarning: Directory already exists. 
> In testCubeCutout>testPreCalcCuboid_NoPad_Start_CutoutMerge (line 520)
>   In FunctionHandleTestCase/runTestCase (line 112)
>   In TestCase/run (line 74)
>   In TestSuite/run (line 85)
>   In runtests (line 126)
>   In RUN_TESTS (line 258)
>   In run (line 96) 
> F
> FAILED in 30.466 seconds.

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/packages/testCubeCutout.m
Name:     testPreCalcCuboid_NoPad_Start_CutoutOnly

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/packages/testCubeCutout.m at line 192

Undefined function 'cubeCutoutPreprocessCuboid' for input arguments of type 'char'.

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/packages/testCubeCutout.m
Name:     testPreCalcCuboid_NoPad_End_CutoutOnly

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/packages/testCubeCutout.m at line 298

Undefined function 'cubeCutoutPreprocessCuboid' for input arguments of type 'char'.

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/packages/testCubeCutout.m
Name:     testPreCalcCuboid_Pad_Start_CutoutOnly

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/packages/testCubeCutout.m at line 359

Undefined function 'cubeCutoutPreprocessCuboid' for input arguments of type 'char'.

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/packages/testCubeCutout.m
Name:     testPreCalcCuboid_Pad_End_CutoutOnly

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/packages/testCubeCutout.m at line 463

Undefined function 'cubeCutoutPreprocessCuboid' for input arguments of type 'char'.

===== Test Case Failure =====
Location: /Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/packages/testCubeCutout.m
Name:     testPreCalcCuboid_NoPad_Start_CutoutMerge

/Users/jovo/Research/Projects/Web-stuff/CAJAL/test/matlab/packages/testCubeCutout.m at line 523

Undefined function 'cubeCutoutPreprocessCuboid' for input arguments of type 'char'.

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

 ## TEST FAILURES EXIST ##

**Comment by alexbaden** [comment]
Make sure the target server is brainviz1 in testOCP.m and then run

```
RUN_TESTS('testOCP') 
```

**Comment by jovo** [comment]
it worked the 2nd time, so maybe it is resolved?

On Mon, Jul 13, 2015 at 9:53 PM, Alex Baden notifications@github.com
wrote:

>  Make sure the target server is brainviz1 in testOCP.m and then run
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/CAJAL/issues/29#issuecomment-121109638
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York

**Comment by alexbaden** [comment]
Closing in favor of other test failure issues / there have been a lot of changes since this issue.
