### ISSUE TITLE
New Branch Test Failures?

### ISSUE THREAD

**Issue by wrgr** [neurodata/CAJAL#38]
Against brainviz1...probably doing something wrong?
## Starting Unit Tests

1 Test Suites selected out of 16 Test Suites discovered

<><><><> Running Test Suite 1 of 1 <><><><><><><><><><>
Test suite: testOCP
Test suite location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
10-Aug-2015 16:17:37

Starting test run with 69 test cases.
.......FF......F.FFF
..FFF..FF...F.......
..FF.FFFFF..........
.......F.
FAILED in 248.106 seconds.

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteGenericCutout

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 370

Inputs are not equal.

First input:
     0

Second input:
        1340

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteGenericVoxelList

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 423

Inputs are not equal.

First input:
   102

Second input:
    51

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteSynapseCutout

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 624

Inputs are not equal.

First input:
[1008x1 double]

Second input:
[1008x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteSynapseVoxelList

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 709

Inputs are not equal.

First input:
   102

Second input:
    51

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadNewSynapseWithExistingID

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 768

Inputs are not equal.

First input:
[1008x1 double]

Second input:
[1008x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadUpdateSynapse

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 831

Inputs are not equal.

First input:
[1008x1 double]

Second input:
[1008x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteSegmentCutout

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 939

Inputs are not equal.

First input:
[4630x1 double]

Second input:
[4630x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteSegmentVoxelList

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 990

Inputs are not equal.

First input:
   102

Second input:
    51

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadUpdateSegment

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 1045

Inputs are not equal.

First input:
[4630x1 double]

Second input:
[4630x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteOrganelleCutout

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 1183

Inputs are not equal.

First input:
[8000x1 double]

Second input:
[8000x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteOrganelleVoxelList

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 1230

Inputs are not equal.

First input:
   102

Second input:
    51

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testAnnotationSlice

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 1366

Inputs are not equal.

First input:
[441x1 double]

Second input:
[736x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testCutoutvsDense

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 1819

Inputs are not equal.

First input:
     0

Second input:
        1377

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testCutoutvsDenseSingleSlice

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 1908

Inputs are not equal.

First input:
     0

Second input:
        1378

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testConflictWriteOptions

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 2058

Inputs are not equal.

First input:
     0

Second input:
        1382

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testBatchMode

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 2162

Inputs are not equal.

First input:
[1600x1 double]

Second input:
[1600x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     TestDeleteBatchMode

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 2257

Inputs are not equal.

First input:
[1600x1 double]

Second input:
[1600x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testSingleCutoutChunking

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 2325

Inputs are not equal.

First input:
[50000x1 double]

Second input:
[50000x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testSingleVoxelListChunking

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 2378

Inputs are not equal.

First input:
       60000

Second input:
       50000

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testImageDataUpload

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 3120

Inputs are not equal.

First input:
      312500

Second input:
      250000

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

 ## TEST FAILURES EXIST ##

**Comment by alexbaden** [comment]
The first thing to do is immediately run tests again. Do you get the same
output?

**Comment by wrgr** [comment]
seems like:

1 Test Suites selected out of 16 Test Suites discovered

<><><><> Running Test Suite 1 of 1 <><><><><><><><><><>
Test suite: testOCP
Test suite location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
10-Aug-2015 16:29:36

Starting test run with 69 test cases.
.......FF......F.FFF
..FFF..FF...F.......
..FF.FFFFF..........
.......F.
FAILED in 241.678 seconds.

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteGenericCutout

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 370

Inputs are not equal.

First input:
     0

Second input:
        1454

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteGenericVoxelList

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 423

Inputs are not equal.

First input:
   102

Second input:
    51

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteSynapseCutout

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 624

Inputs are not equal.

First input:
[1008x1 double]

Second input:
[1008x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteSynapseVoxelList

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 709

Inputs are not equal.

First input:
   102

Second input:
    51

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadNewSynapseWithExistingID

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 768

Inputs are not equal.

First input:
[1008x1 double]

Second input:
[1008x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadUpdateSynapse

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 831

Inputs are not equal.

First input:
[1008x1 double]

Second input:
[1008x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteSegmentCutout

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 939

Inputs are not equal.

First input:
[4630x1 double]

Second input:
[4630x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteSegmentVoxelList

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 990

Inputs are not equal.

First input:
   102

Second input:
    51

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadUpdateSegment

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 1045

Inputs are not equal.

First input:
[4630x1 double]

Second input:
[4630x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteOrganelleCutout

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 1183

Inputs are not equal.

First input:
[8000x1 double]

Second input:
[8000x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testUploadDownloadDeleteOrganelleVoxelList

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 1230

Inputs are not equal.

First input:
   102

Second input:
    51

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testAnnotationSlice

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 1366

Inputs are not equal.

First input:
[441x1 double]

Second input:
[736x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testCutoutvsDense

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 1819

Inputs are not equal.

First input:
     0

Second input:
        1491

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testCutoutvsDenseSingleSlice

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 1908

Inputs are not equal.

First input:
     0

Second input:
        1492

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testConflictWriteOptions

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 2058

Inputs are not equal.

First input:
     0

Second input:
        1496

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testBatchMode

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 2162

Inputs are not equal.

First input:
[1600x1 double]

Second input:
[1600x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     TestDeleteBatchMode

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 2257

Inputs are not equal.

First input:
[1600x1 double]

Second input:
[1600x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testSingleCutoutChunking

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 2325

Inputs are not equal.

First input:
[50000x1 double]

Second input:
[50000x1 double]

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testSingleVoxelListChunking

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 2378

Inputs are not equal.

First input:
       60000

Second input:
       50000

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal/test/matlab/api/testOCP.m
Name:     testImageDataUpload

/Users/graywr1/code/cajal/test/matlab/api/testOCP.m at line 3120

Inputs are not equal.

First input:
      312500

Second input:
      250000

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

**Comment by alexbaden** [comment]
Which branch is this?

**Comment by wrgr** [comment]
- dev-180-RC2  [is this right?]

Best,
Will

**Comment by alexbaden** [comment]
Yeah, that's right. Not sure what's going on. I'll have to look into it.
Give me a few hours...

**Comment by alexbaden** [comment]
Also -- what command are you using to run tests?

**Comment by wrgr** [comment]
RUN_TESTS('testOCP')

Best,
Will

**Comment by alexbaden** [comment]
Very strange:

```
Starting test run with 69 test cases.
....................
.........F.F........
....................
.........
```

The two failures there are the same two failures we've had over and over again (downloading kasthuri cutout and comparing). I'm not concerned, because (1) this is the dev server and kasthuri data isn't being used for production and (2) the upload/download cutout tests work fine. 

I just ran that test between CAJAL 1.8 and current OCP master. brainviz is a little out of date from current master. When I get home (currently stuck in Atlanta watching the lightning) I'll run against brainviz. 

One last thing to try is download a clean copy of cajal from the dev branch and start a new matlab instance. I wonder if something is being "cached"?

**Comment by alexbaden** [comment]
I have this down to 5 failures (2 existing). I suspect most of these have to do with the data that exists on brainviz (all still pass on my local copy), especially since we modified kasthuri11 dataset parameters.

**Comment by alexbaden** [comment]
The vast majority of these seem to be related to OCP v0.8 bugs. I am closing this issue -- after fixing bounds checking, I will re-run the unit tests and open an individual issue for each one that fails.

**Comment by wrgr** [comment]
That's right, although possibly all the same bug, so maybe wait for
resolution of larger issue.

Best,
Will
