### ISSUE TITLE
Upload/Download Bug

### ISSUE THREAD

**Issue by wrgr** [neurodata/CAJAL#43]
Tests to put and then get same data don't match.  Works on v1.7 with same code.  Urgently needs to be fixed.

**Comment by alexbaden** [comment]
Does put and get work with master on brainviz?

Alex

**Comment by wrgr** [comment]
correct.  This works on 1.7 and brainviz.  So I'm guessing that something
changed on the backend interface that is either a bug or we need to fix.

Best,
Will

**Comment by alexbaden** [comment]
CAJAL 1.7?

Can you do a test of current master against brainviz?

Alex

**Comment by wrgr** [comment]
Trying to do two things - master + brainviz works!

**Comment by wrgr** [comment]
Ok - I'm fairly certain now of three things:
1.  This is impacting core cajal functionality and cajal can't be used until this is resolved
2.  It appears to be a mismatch in fundamental code between CAJAL and OCP.  Something changed between 1.7 and 1.8...nothing obvious client side
3.  It impacts 22 of the 23 failing tests, so hopefully fixing this one thing will get us in a position to do science.

**Comment by alexbaden** [comment]
Fixed w/ latest OCP master (thanks to @kunallillaney ).
