### ISSUE TITLE
investigate overlay issue 

### ISSUE THREAD

**Issue by wrgr** [neurodata/CAJAL#47]
overlay query is likely not functional right now.

**Comment by alexbaden** [comment]
por que?

**Comment by wrgr** [comment]
Was worried because of the new syntax.  These unit tests actually just passed, so things are ok.  False alarm.

**Comment by alexbaden** [comment]
Woooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooootooooooooooooooooooooooooooooooooooooooooooooooooo
ooooooot!

**Comment by wrgr** [comment]
+1

Best,
Will

2015-08-21 18:39 GMT-04:00 Alex Baden notifications@github.com:
