### ISSUE TITLE
Get last z slice

### ISSUE THREAD

**Issue by wrgr** [neurodata/CAJAL#48]
Bounds checking prevents this (I think) right now.

**Comment by alexbaden** [comment]
Yeah, that sounds possible. Easy enough to fix, looking now...

Alex

**Comment by alexbaden** [comment]
@willgray 

Right now, all of the CAJAL calls are consistent:

```
imgDims = dbInfo.DATASET.IMAGE_SIZE(this.resolution);
                            imgOffsets = dbInfo.DATASET.OFFSET(this.resolution);
                            if this.xRange(1) < imgOffsets(1)
                                valid = false;
                                msg = sprintf('%s[E] Lower X Range out of valid dataset range.\n',msg);
                            end
                            if this.xRange(2) > imgDims(1)
                                valid = false;
                                msg = sprintf('%s[E] Upper X Range out of valid dataset range.\n',msg);
                            end
                            if this.yRange(1) < imgOffsets(2)
                                valid = false;
                                msg = sprintf('%s[E] Lower Y Range out of valid dataset range.\n',msg);
                            end
                            if this.yRange(2) > imgDims(2)
                                valid = false;
                                msg = sprintf('%s[E] Upper Y Range out of valid dataset range.\n',msg);
                            end
                            if this.zRange(1) < imgOffsets(3)
                                valid = false;
                                msg = sprintf('%s[E] Lower Z Range out of valid dataset range.\n',msg);
                            end
                            if this.zRange(2) > imgDims(3) 
                                valid = false;
                                msg = sprintf('%s[E] Upper Z Range out of valid dataset range.\n',msg);
                            end
```

Let's say I have a dataset that has offsets (1,1,1) and image dimensions (100,100,100). I assume this means there is data at both voxel (1,1,1) and (100,100,100). So, if I wanted to get just the voxel at (100,100,100), what would I query in OCP? And similarly for (1,1,1)? @kunallillaney @randalburns

**Comment by wrgr** [comment]
I think:

For (1,1,1), your setCutout is [1,2],[1,2],[1,2].
For (100,100,100), your setCutout is [100,101], [100,101],[100,101], thus
the trouble.

We notice this on the z axis, but probably true for x,y as well.  (0-100
actually has 101 pixels, not 100)

**Comment by alexbaden** [comment]
I think so, too. Worth testing with an example dataset? Possibly use ocpy
to post and cajal to get, then vice versa? I'll try and make the changes on
the dev branch this afternoon.

**Comment by wrgr** [comment]
so all development on cajal (I hope) is on cajal-docs - do you want to do
branch management differently?

Because we are documenting with sphinx, it's annoying...we'll wind up
touching pretty much every file, so pull requests from two branches will be
horrible to merge.

**Comment by alexbaden** [comment]
Closing in favor of #49
