### ISSUE TITLE
testUploadDownloadProbMapCutout unit test FAILS

### ISSUE THREAD

**Issue by wrgr** [neurodata/CAJAL#54]
Test case fails - critical for science.  Likely due to a real bug in the underlying code.  other issues address the backend handling, which appear resolved.

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal-docs/test/matlab/api/testOCP.m
Name:     testUploadDownloadProbMapCutout

/Users/graywr1/code/cajal-docs/api/matlab/ocp/OCPHdf.m at line 888
/Users/graywr1/code/cajal-docs/api/matlab/ocp/OCPHdf.m at line 69
/Users/graywr1/code/cajal-docs/api/matlab/ocp/OCP.m at line 1912
/Users/graywr1/code/cajal-docs/api/matlab/ocp/OCP.m at line 1232
/Users/graywr1/code/cajal-docs/test/matlab/api/testOCP.m at line 255

Undefined function or variable "h5Handle".

**Comment by alexbaden** [comment]
Just had to change probmap to image, and make some minor changes in OCPHDf.m . Seems okay now. All pushed to master -- I can handle merging tomorrow w/ you. 

The db on ocp.me was also messed up -- had apiUnitTestsKasthuriProb6 instead of apiUnitTestsKasthuriProb .
