### ISSUE TITLE
decide whether we want to keep tests that scrape kasthuri11 data

### ISSUE THREAD

**Issue by alexbaden** [neurodata/CAJAL#57]
Or are we happy with the upload / download tests? If we are happy with the scraping tests, we need to take a new kat11 reference dataset.

**Comment by wrgr** [comment]
Tell me more?  I like the existing tests ok.  What's wrong with the
existing reference set?  I think these tests need to exist in some form,
but am less worried because we only need to validate cajal - backend unit
tests robustly test this functionality.

Best,
Will

**Comment by alexbaden** [comment]
Right now they aren't passing because the existing objects have a datatype,
and I just deleted datatype to try and keep the enum simple. But, that's
easy enough to fix -- grab a new cutout and save it as a .mat.

The bigger issue is you need kasthuri11 at res1 to pass the test (of course
we could use res5 or res7). That means someone who stands up their own
instance of OCP and CAJAL will never have all tests pass, because they
won't have kasthuri data. That's why I'm leaning towards removing them...

**Comment by alexbaden** [comment]
My vote is no. If the unit tests pass, the data should be good. If we want to build separate tests for making sure specific data sets are in good shape, that's fine -- but I'm going to close this issue. Reopen if anyone feels strongly!
