### ISSUE TITLE
RAMON Synapse cast error

### ISSUE THREAD

**Issue by wrgr** [neurodata/CAJAL#62]
Uploading synapses sometimes results in a type error, similar to what we saw this past week.  To duplicate error, try running the following code snippet on a clean channel multiple times, with and without the explicit cast to uint32:

```
d = zeros(200,200,5);
d(30:170,30:170,:) = 1;

% Create an empty RAMONSynapse object
s1 = RAMONSynapse()

% Set the objects properties as desired.
s1.setCutout(uint32(d));
s1.setXyzOffset([xstart+1000 ystart zstart]);
s1.setResolution(1);

s1.setSynapseType(eRAMONSynapseType.excitatory);
s1.setSeeds([2 4 6 3]);
s1.setConfidence(.8);


%% Upload a Synapse
%Simply passing the RAMON object (or any RAMON object really...) will upload
%the data and create an annotation.  The database will assign an ID as long
%as the ID was empty in the RAMON object.
id1 = oo.createAnnotation(s1);
```

**Comment by wrgr** [comment]
A more thorough test - checkout the `./examples/demoScript.m` file in the cajal-docs branch.  It should work multiple times with no issues.

**Comment by alexbaden** [comment]
I'm not able to reproduce on a clean annotation channel as you described. Is it possible this wasn't using the latest version of CAJAL? I checked through all the HDF5 calls and they're all typecast, so you shouldn't need to explicitly cast to uint32 in setCutout.

**Comment by wrgr** [comment]
i am still confused.  I ran on cajal-docs branch just now - demoscript.m works the first time through, but fails on line 101, due seemingly to this issue somewhere downstream.  I can help debug if needed, but this seems at least reproducible.

I deleted and recreated the channel.

**Comment by alexbaden** [comment]
Can you paste the error here? Or send me the webpage/html that is displayed
at OCP?

**Comment by wrgr** [comment]
Yah.  Here you go.  Eager to fix this - am in Oxford on Sunday to do a live demo and hoping to be able to share all of this.  See traceback below.

Environment:

Request Method: POST
Request URL: http://openconnecto.me/ocp/ocpca/cajal_demo/anno/overwrite/

Django Version: 1.8.4
Python Version: 2.7.3
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'ocpca',
 'overlay',
 'synaptogram',
 'catmaid',
 'registration',
 'ocpuser',
 'djcelery',
 'ocpviz')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')

Traceback:
File "/usr/share/ocp/virtualenvs/ocp/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
   File "./ocpca/views.py" in annotation
2.     raise OCPCAError("Unknown exception in annotation")

Exception Type: OCPCAError at /ocpca/cajal_demo/anno/overwrite/
Exception Value: 'Unknown exception in annotation'

**Comment by wrgr** [comment]
Update: when I post a synapse (similar to the above) - prior to packaging, it's of type uint32 (I cast to be certain).  

When I pull down the data the result is a double in CAJAL.  So either CAJAL is packing/unpacking incorrectly or something funky on the backend.  I believe it's CAJAL, because on inspection of the raw HDF5 file, I confirm that the data values are  uint32.  Hopefully this is an easy fix.

**Comment by wrgr** [comment]
Line 1495 of OCPHdf:  
     ramonObj.setCutout((permute(double(data),[2 1 3])));

The cast to double is weird.  And possibly related to this issue.  But I patched it (took out the cast) and error still recurs.  Fine on the first pass through demoscript, error on the second, seemingly because junk data is getting written or received.

**Comment by alexbaden** [comment]
OCP bug. Has been fixed!
