### ISSUE TITLE
More typecasting problems

### ISSUE THREAD

**Issue by wrgr** [neurodata/CAJAL#65]
Anish reports a weird error when uploading synapses.  We thought it might be the NX3 data being interpreting as a voxellist.  But it's not.  I think it's pre-existing junk data, because he was uploading random data, which had type double, and I think we weren't checking.

Thoughts?

https://gist.github.com/aksimhal/50d196267a9ef46af754

**Comment by alexbaden** [comment]
Duplicate of #64

**Comment by wrgr** [comment]
So all fixed? These were on rc3, so beyond the earlier fixes. I don't
observe this with my workflows (I cast and check).

**Comment by alexbaden** [comment]
No, I'm working on it now. Going to put all updates in #64 (edited)
