### ISSUE TITLE
CAJAL doesn't clean up thousands of OCPHdf_RAMON_tp*.h5 temporary files it creates

### ISSUE THREAD

**Issue by kkutten1** [neurodata/CAJAL#69]
CAJAL 1.8.0 RC3 creates thousands of OCPHdf_RAMON_tp*.h5 temporary files in the /tmp/ when I'm uploading image data on a Ubuntu 12.04 machine.  Since the machine is rarely rebooted, the files accumulate, take up space and slow down the file system. Right now I manually delete them to deal with this problem.

**Comment by wrgr** [comment]
That's true. We decided to do it that way for traceability. Open to a
discussion. At the least, we could provide instructions to make a cron job
or similar to do the cleanup?

@all - many (most) servers have a cleanup policy, so this only really
affects clients who upload lots of data, which is perhaps fairly unusual?

**Comment by wrgr** [comment]
obe.
