### ISSUE TITLE
rgb32 data not supported

### ISSUE THREAD

**Issue by wrgr** [neurodata/CAJAL#75]
This has been on the enhancements list for some time.  We now have the first examples of this data.  Enhancement request, not stopping science, but might make it harder in the near term.

HDF5 alternatives exist.  Putting here so it doesn't get lost.

@alexbaden @jovo

**Comment by wrgr** [comment]
Discovered while exploring manno limitations, but applies generally across cajal...

**Comment by jovo** [comment]
yah, i doubt we will ever care, because even if data is RGB32, we can always ingest as multichannel.  i guess this might matter when we ingest guardians of the galaxy....
@j6k4m8
