### ISSUE TITLE
update wiki to replace ocpMatlab everywhere with cajal

### ISSUE THREAD

**Issue by jovo** [neurodata/CAJAL#9]

**Comment by wrgr** [comment]
How can I change the name of a wiki page?  Wanted to change link name and
page destinations....

Best,
Will

On Wed, Apr 15, 2015 at 3:29 PM, joshua vogelstein <notifications@github.com

**Comment by alexbaden** [comment]
Create new page with new name. Delete old page (by saving it empty).
